
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndygqfwwshjngzukypyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keWdxZnd3c2hqbmd6dWt5cHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTA5MDQsImV4cCI6MjA1ODY2NjkwNH0.1wXFhk1MxLheHymXSY4UKG5u1XWYOnqRRyhrO9xmwCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add this type augmentation to support direct access to quote_requests table
// while we wait for the Supabase types to be regenerated
declare module '@supabase/supabase-js' {
  interface PostgrestQueryBuilder<Schema extends Record<string, unknown>> {
    from<TableName extends string>(
      relation: TableName
    ): PostgrestQueryBuilder<Schema>
  }
}
